aws_profile = "default"
aws_region = "us-east-1"
env = "testnut"
namespace = "nutcorp"
terraform_version = "1.0.10"

[infra.terraform]
aws_profile = "default"
aws_region = "us-east-1"
terraform_version = "1.0.10"

[service.squiby]
type = "ecs"
env = {env1 = "value1", env2 = "value2"}
path = "./project/giblin"
subnets = "infra"
vpc = "infra"
