aws_profile = "default"
aws_region = "us-east-1"
env = "testnut"
namespace = "nutcorp"
terraform_version = "1.0.10"

[infra.terraform]
aws_profile = "default"
aws_region = "us-east-1"
terraform_version = "1.0.10"

[app.goblin]
type = "ecs"
path = "./projects/goblin"
