aws_region = "us-east-1"
namespace = "testnut"
terraform_version = "1.1.7"

[app.squibby]
type = "ecs"
path = "./apps/squibby"

[app.goblin]
type = "ecs"
path = "./apps/goblin"

[serverless.pecan]
path = "./apps/pecan"
node_version = "16"

