name: "Build IZE on release"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
on:
  release:
    types: [created]

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/0.0.0-dev') != true
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
       go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release -f .goreleaser.yml --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
        SHORT_SHA: ${{ env.SHORT_SHA }}

    - name: create docs
      run: |
        mkdir -p commands
        go run ./cmd gen doc

    - name: convert MD to HTML
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: commands
        output_dir: docs
        # Default is true, can set to false to only get PDF files
        build_html: true

    - name: remove pdfs and rename links #This needs because action creates PDF by default
      run: |
        cd docs
        sudo rm *.pdf
        sudo mv ize.html index.html
        sudo sed -i 's/.md/.html/g' *
        sudo sed -i 's/ize.html/index.html/g' *

    - name: Pushes ize commands to ize.sh
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
      with:
        source_file: 'docs'
        destination_repo: 'hazelops/ize.sh'
        destination_folder: 'public'
        user_email: 'ize@hazelops.com'
        user_name: 'ize'
        commit_message: 'Add commands from Ize'

  code-coverage-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        continue-on-error: true
        run: go build -v ./...

      - name: Test
        continue-on-error: true
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  create-jira-release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: Rorychan/jira-releases-action@v1
        continue-on-error: true
        with:
          jira-server: 'https://hazelops.atlassian.net'
          jira-email: 'dmitry@hazelops.com'
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          project-name: 'IZE'
          release-name: ${{ github.event.release.name }}
          is-released: true
      - name: Sleep for 7 minutes
        uses: whatnick/wait-action@master
        with:
          time: '7m'
