name: "Build IZE on push"
env:
  GOPATH: ~/go
on:
  push:
    branches:
      - main

jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -o ./ize ./cmd
    - name: Upload bin to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: digest
        path: ./ize.*
