name: "Build & Publish dev Release"
on:
  release:
    types: [created]

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/0.0.0-dev')
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
       go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set env
      run: |
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release -f .goreleaser_push.yml --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        RELEASE_VERSION: "development"
        FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
        GIT_SHA: ${{ env.SHORT_SHA }}
        GITHUB_ACTOR: ${{ github.actor }}
