name: "Build IZE on release"

on:
  release:
    types: [created]

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/0.0.0-dev') != true
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
       go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release -f .goreleaser.yml --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}

    - name: create docs
      run: |
        mkdir -p commands
        go run ./cmd gendoc

    - name: convert MD to HTML
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: commands
        output_dir: docs
        # Default is true, can set to false to only get PDF files
        build_html: true

    - name: remove pdfs #This needs because action creates PDF by default
      run: |
        cd docs
        sudo rm *.pdf

    - name: Pushes ize commands to ize.sh
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
      with:
        source_file: 'docs'
        destination_repo: 'hazelops/ize.sh'
#        destination_folder: 'content'
        user_email: 'ize@hazelops.com'
        user_name: 'ize'
        commit_message: 'Add commands from Ize'
