name: "Create dev release"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
on:
  push:
    branches:
      - main
jobs:
  create_on_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Delete release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true # default: false
        tag_name: 0.0.0-dev # tag name to delete
        repo: hazelops/ize # target repo (optional). defaults to repo running this action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: install gemfury
      run: |
        sudo apt-get -y install ruby
        sudo gem install gemfury

    - name: list dev packages # Show list of linux packages in Gemfury
      run: |
        fury versions deb:ize  --api-token=${{ secrets.FURY_ACCESS_TOKEN }}
        fury versions rpm:ize  --api-token=${{ secrets.FURY_ACCESS_TOKEN }}
      continue-on-error: true

    - name: yank old versions of dev # Since we have AMD64 and ARM64 versions of ize - we need to run every remove action twice
      run: |
        fury yank deb:ize --version=0.0.0~dev --api-token=${{ secrets.FURY_ACCESS_TOKEN }}
        fury yank deb:ize --version=0.0.0~dev --api-token=${{ secrets.FURY_ACCESS_TOKEN }}
        fury yank rpm:ize --version=0.0.0~dev-1 --api-token=${{ secrets.FURY_ACCESS_TOKEN }}
        fury yank rpm:ize --version=0.0.0~dev-1 --api-token=${{ secrets.FURY_ACCESS_TOKEN }}
      continue-on-error: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: 0.0.0-dev
        release_name: Dev Release
        prerelease: true
        body: |
          Most recent dev release
