name: "Create dev release"
on:
  push:
    branches:
      - main
jobs:
  create_on_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Delete release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true # default: false
        tag_name: 0.0.0-dev # tag name to delete
        repo: hazelops/ize # target repo (optional). defaults to repo running this action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: 0.0.0-dev
        release_name: Dev Release
        body: |
          Most recent dev release
