name: "Tests: Unit"
defaults:
  run:
    shell: bash

env:
  AWS_PROFILE: default
  AWS_REGION: us-east-1

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
# TODO: re-enable other platforms after Ubuntu is working fine
#          - macos-latest
#          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate
        run: |
          go generate ./...

      - name: Build
        run: |
          go mod download
          make bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ize-${{ matrix.os }}-${{ github.sha }}
          path: ${{ github.workspace }}/ize

  # TODO: this should be executed before the release and fail in proper cases
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Generate Test SSH Key
        run: ssh-keygen -q -f ~/.ssh/id_rsa

      - name: Test
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
