name: "Test IZE"

env:
  AWS_REGION: us-east-1
  ENV: dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create AWS Profile
        run: make aws.profile

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build -o ./ize ./cmd

      - name: Run builded ize
        run: | 
          cd examples/simple-monorepo
          ize terraform init
